version: '3.8'

services:
  costloci-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: costloci-backend
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - "3001:3001"
    networks:
      - costloci-network

  costloci-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: costloci-frontend
    ports:
      - "5180:5180"
    networks:
      - costloci-network

networks:
  costloci-network:
    driver: bridge
